sudo: required
services:
  - docker

before_install:
  - docker build -t perzefi/docker-react -f Dockerfile.dev .

script:
  - docker run perzefi/docker-react npm run test -- --coverage --watchAll=false