sudo: required
services:
  - docker

before_install:
  - docker build -t perzefi/docker-react -f Dockerfile.dev .

script:
  - docker run perzefi/docker-react npm run test -- --coverage --watchAll=false

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-406118569965"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

